"""Auto-generated localization keys.

This file is generated by flet-l10n. Do not edit manually.
Run `flet-l10n generate` to regenerate.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from flet_l10n import Localizations


class L10nKeys:
    """Typed keys for localization strings.
    
    This class provides string constants for all translation keys,
    enabling IDE autocompletion and preventing typos.
    
    Usage:
        from l10n_keys import L10nKeys
        
        l10n.t(L10nKeys.appTitle)
        l10n.t(L10nKeys.welcome, name="User")
    """

    # The title of the application
    appTitle = "appTitle"

    # Display item count with pluralization
    # Placeholders: count
    itemCount = "itemCount"

    # Welcome message with user name
    # Placeholders: name
    welcome = "welcome"

    @classmethod
    def all_keys(cls) -> list[str]:
        """Get all available translation keys.
        
        Returns:
            List of all translation key strings
        """
        return [
            cls.appTitle,
            cls.itemCount,
            cls.welcome,
        ]


# Convenience instance for direct key access
Keys = L10nKeys()
