"""Code generator for creating typed localization keys class from ARB files."""

import json
from pathlib import Path
from typing import Any

from .arb_parser import ARBParser, ARBEntry
from .exceptions import ARBParseError
from .config import L10nConfig


class L10nKeysGenerator:
    """Generates a Python class with typed localization keys from ARB files."""

    def __init__(self, template_arb_path: Path):
        """Initialize the generator.

        Args:
            template_arb_path: Path to the template ARB file (typically English)
        """
        self.template_path = template_arb_path
        self.parser = ARBParser()

    def generate(self, output_path: Path, class_name: str = "L10nKeys") -> None:
        """Generate the keys class file.

        Args:
            output_path: Path where to save the generated Python file
            class_name: Name of the generated class (default: L10nKeys)
        """
        # Parse the template ARB file
        entries = self.parser.parse_file(self.template_path)

        # Generate the Python code
        code = self._generate_class_code(entries, class_name)

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(code)

    def _generate_class_code(
        self, entries: dict[str, ARBEntry], class_name: str
    ) -> str:
        """Generate the Python class code.

        Args:
            entries: Dictionary of ARB entries
            class_name: Name of the class

        Returns:
            Generated Python code as string
        """
        lines = [
            '"""Auto-generated localization keys.',
            "",
            "This file is generated by flet-l10n. Do not edit manually.",
            "Run `flet-l10n generate` to regenerate.",
            '"""',
            "",
            "from typing import TYPE_CHECKING",
            "",
            "if TYPE_CHECKING:",
            "    from flet_l10n import Localizations",
            "",
            "",
            f"class {class_name}:",
            f'    """Typed keys for localization strings.',
            "    ",
            "    This class provides string constants for all translation keys,",
            "    enabling IDE autocompletion and preventing typos.",
            "    ",
            "    Usage:",
            f"        from l10n_keys import {class_name}",
            "        ",
            f"        l10n.t({class_name}.appTitle)",
            f'        l10n.t({class_name}.welcome, name="User")',
            '    """',
            "",
        ]

        # Sort entries by key for consistent output
        sorted_entries = sorted(entries.items(), key=lambda x: x[0])

        # Generate constants for each key (using camelCase as-is)
        for key, entry in sorted_entries:
            # Add docstring if description is available
            if entry.description:
                lines.append(f"    # {entry.description}")

            # Add placeholder information if available
            if entry.placeholders:
                placeholder_names = ", ".join(entry.placeholders.keys())
                lines.append(f"    # Placeholders: {placeholder_names}")

            # Add the constant (keep original camelCase name)
            lines.append(f'    {key} = "{key}"')
            lines.append("")

        # Add helper method to get all keys
        lines.extend(
            [
                "    @classmethod",
                "    def all_keys(cls) -> list[str]:",
                '        """Get all available translation keys.',
                "        ",
                "        Returns:",
                "            List of all translation key strings",
                '        """',
                "        return [",
            ]
        )

        for key, _ in sorted_entries:
            lines.append(f"            cls.{key},")

        lines.extend(
            [
                "        ]",
                "",
                "",
                "# Convenience instance for direct key access",
                f"Keys = {class_name}()",
            ]
        )

        return "\n".join(lines) + "\n"


def generate_keys_class(
    template_arb: Path, output_path: Path, class_name: str = "L10nKeys"
) -> None:
    """Generate localization keys class from ARB file.

    Args:
        template_arb: Path to template ARB file
        output_path: Path for generated Python file
        class_name: Name of the generated class
    """
    generator = L10nKeysGenerator(template_arb)
    generator.generate(output_path, class_name)
